<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: casbin.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\Array2DReply\d instead.
     * @deprecated
     */
    class Array2DReply_d {}
}
class_exists(Array2DReply\d::class);
@trigger_error('Proto\Array2DReply_d is deprecated and will be removed in the next major release. Use Proto\Array2DReply\d instead', E_USER_DEPRECATED);

