<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: casbin.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.BoolReply</code>
 */
class BoolReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool res = 1;</code>
     */
    private $res = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $res
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Casbin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool res = 1;</code>
     * @return bool
     */
    public function getRes()
    {
        return $this->res;
    }

    /**
     * Generated from protobuf field <code>bool res = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setRes($var)
    {
        GPBUtil::checkBool($var);
        $this->res = $var;

        return $this;
    }

}

