<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: casbin.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.NewAdapterRequest</code>
 */
class NewAdapterRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string adapterName = 1;</code>
     */
    private $adapterName = '';
    /**
     * Generated from protobuf field <code>string driverName = 2;</code>
     */
    private $driverName = '';
    /**
     * Generated from protobuf field <code>string connectString = 3;</code>
     */
    private $connectString = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $adapterName
     *     @type string $driverName
     *     @type string $connectString
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Casbin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string adapterName = 1;</code>
     * @return string
     */
    public function getAdapterName()
    {
        return $this->adapterName;
    }

    /**
     * Generated from protobuf field <code>string adapterName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAdapterName($var)
    {
        GPBUtil::checkString($var, True);
        $this->adapterName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string driverName = 2;</code>
     * @return string
     */
    public function getDriverName()
    {
        return $this->driverName;
    }

    /**
     * Generated from protobuf field <code>string driverName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDriverName($var)
    {
        GPBUtil::checkString($var, True);
        $this->driverName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string connectString = 3;</code>
     * @return string
     */
    public function getConnectString()
    {
        return $this->connectString;
    }

    /**
     * Generated from protobuf field <code>string connectString = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setConnectString($var)
    {
        GPBUtil::checkString($var, True);
        $this->connectString = $var;

        return $this;
    }

}

