<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: casbin.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.SimpleGetRequest</code>
 */
class SimpleGetRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 enforcerHandler = 1;</code>
     */
    private $enforcerHandler = 0;
    /**
     * Generated from protobuf field <code>string pType = 2;</code>
     */
    private $pType = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $enforcerHandler
     *     @type string $pType
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Casbin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 enforcerHandler = 1;</code>
     * @return int
     */
    public function getEnforcerHandler()
    {
        return $this->enforcerHandler;
    }

    /**
     * Generated from protobuf field <code>int32 enforcerHandler = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setEnforcerHandler($var)
    {
        GPBUtil::checkInt32($var);
        $this->enforcerHandler = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pType = 2;</code>
     * @return string
     */
    public function getPType()
    {
        return $this->pType;
    }

    /**
     * Generated from protobuf field <code>string pType = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPType($var)
    {
        GPBUtil::checkString($var, True);
        $this->pType = $var;

        return $this;
    }

}

