<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: casbin.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UserRoleRequest</code>
 */
class UserRoleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 enforcerHandler = 1;</code>
     */
    private $enforcerHandler = 0;
    /**
     * Generated from protobuf field <code>string user = 2;</code>
     */
    private $user = '';
    /**
     * Generated from protobuf field <code>string role = 3;</code>
     */
    private $role = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $enforcerHandler
     *     @type string $user
     *     @type string $role
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Casbin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 enforcerHandler = 1;</code>
     * @return int
     */
    public function getEnforcerHandler()
    {
        return $this->enforcerHandler;
    }

    /**
     * Generated from protobuf field <code>int32 enforcerHandler = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setEnforcerHandler($var)
    {
        GPBUtil::checkInt32($var);
        $this->enforcerHandler = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user = 2;</code>
     * @return string
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>string user = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string role = 3;</code>
     * @return string
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Generated from protobuf field <code>string role = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkString($var, True);
        $this->role = $var;

        return $this;
    }

}

