<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: casbin.proto

namespace Proto\Array2DReply;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.Array2DReply.d</code>
 */
class d extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string d1 = 1;</code>
     */
    private $d1;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $d1
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Casbin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string d1 = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getD1()
    {
        return $this->d1;
    }

    /**
     * Generated from protobuf field <code>repeated string d1 = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setD1($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->d1 = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(d::class, \Proto\Array2DReply_d::class);

